/**
 * @license
 * Copyright 2019 Pascual de Juan All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as mm from "@magenta/music";

export const TWINKLE_TWINKLE = new mm.NoteSequence({
    notes: [
        { pitch: 60, startTime: 0.0, endTime: 0.5 },
        { pitch: 60, startTime: 0.5, endTime: 1.0 },
        { pitch: 67, startTime: 1.0, endTime: 1.5 },
        { pitch: 67, startTime: 1.5, endTime: 2.0 },
        { pitch: 69, startTime: 2.0, endTime: 2.5 },
        { pitch: 69, startTime: 2.5, endTime: 3.0 },
        { pitch: 67, startTime: 3.0, endTime: 4.0 },
        { pitch: 65, startTime: 4.0, endTime: 4.5 },
        { pitch: 65, startTime: 4.5, endTime: 5.0 },
        { pitch: 64, startTime: 5.0, endTime: 5.5 },
        { pitch: 64, startTime: 5.5, endTime: 6.0 },
        { pitch: 62, startTime: 6.0, endTime: 6.5 },
        { pitch: 62, startTime: 6.5, endTime: 7.0 },
        { pitch: 60, startTime: 7.0, endTime: 8.0 },
    ],
    totalTime: 8,
});

export const TWINKLE_TWINKLE_2 = new mm.NoteSequence({
    notes: [
        { pitch: 60, velocity: 61, startTime: 0.608, endTime: 1.28 },
        { pitch: 48, velocity: 55, startTime: 0.64, endTime: 1.8880000000000001 },
        { pitch: 60, velocity: 71, startTime: 1.28, endTime: 1.8880000000000001 },
        { pitch: 52, velocity: 57, startTime: 0.64, endTime: 2.336 },
        { pitch: 67, velocity: 75, startTime: 1.8880000000000001, endTime: 2.528 },
        { pitch: 60, velocity: 72, startTime: 1.8880000000000001, endTime: 3.168 },
        { pitch: 48, velocity: 65, startTime: 1.8880000000000001, endTime: 3.36 },
        { pitch: 67, velocity: 71, startTime: 2.528, endTime: 3.36 },
        { pitch: 69, velocity: 74, startTime: 3.168, endTime: 3.8080000000000003 },
        { pitch: 60, velocity: 63, startTime: 3.168, endTime: 4.416 },
        { pitch: 69, velocity: 72, startTime: 3.8080000000000003, endTime: 4.5760000000000005 },
        { pitch: 41, velocity: 58, startTime: 3.168, endTime: 5.6000000000000005 },
        { pitch: 48, velocity: 68, startTime: 4.416, endTime: 5.856 },
        { pitch: 67, velocity: 72, startTime: 4.416, endTime: 5.92 },
        { pitch: 65, velocity: 72, startTime: 5.696, endTime: 6.336 },
        { pitch: 60, velocity: 68, startTime: 4.416, endTime: 6.912 },
        { pitch: 41, velocity: 64, startTime: 5.696, endTime: 7.232 },
        { pitch: 65, velocity: 71, startTime: 6.336, endTime: 7.36 },
        { pitch: 64, velocity: 72, startTime: 6.944, endTime: 7.5840000000000005 },
        { pitch: 57, velocity: 68, startTime: 5.696, endTime: 7.712 },
        { pitch: 55, velocity: 64, startTime: 6.944, endTime: 8.224 },
        { pitch: 48, velocity: 65, startTime: 6.944, endTime: 8.32 },
        { pitch: 64, velocity: 74, startTime: 7.5840000000000005, endTime: 8.352 },
        { pitch: 62, velocity: 76, startTime: 8.224, endTime: 8.864 },
        { pitch: 43, velocity: 69, startTime: 8.224, endTime: 9.568 },
        { pitch: 55, velocity: 68, startTime: 8.224, endTime: 9.6 },
        { pitch: 62, velocity: 72, startTime: 8.864, endTime: 9.632 },
        { pitch: 48, velocity: 68, startTime: 9.472, endTime: 10.752 },
        { pitch: 60, velocity: 72, startTime: 9.472, endTime: 10.752 },
        { pitch: 52, velocity: 67, startTime: 9.472, endTime: 10.944 },
        { pitch: 67, velocity: 74, startTime: 10.752, endTime: 11.392 },
        { pitch: 67, velocity: 73, startTime: 11.392, endTime: 12.128 },
        { pitch: 48, velocity: 66, startTime: 10.752, endTime: 12.192 },
        { pitch: 65, velocity: 72, startTime: 12, endTime: 12.64 },
        { pitch: 41, velocity: 62, startTime: 12, endTime: 13.568 },
        { pitch: 60, velocity: 71, startTime: 10.752, endTime: 13.792 },
        { pitch: 64, velocity: 72, startTime: 13.280000000000001, endTime: 13.92 },
        { pitch: 65, velocity: 71, startTime: 12.64, endTime: 13.984 },
        { pitch: 57, velocity: 66, startTime: 12, endTime: 14.208 },
        { pitch: 43, velocity: 67, startTime: 13.280000000000001, endTime: 14.56 },
        { pitch: 55, velocity: 65, startTime: 13.280000000000001, endTime: 14.56 },
        { pitch: 64, velocity: 74, startTime: 13.92, endTime: 14.752 },
        { pitch: 43, velocity: 69, startTime: 14.56, endTime: 15.904 },
        { pitch: 55, velocity: 68, startTime: 14.56, endTime: 15.936 },
        { pitch: 62, velocity: 74, startTime: 14.528, endTime: 15.936 },
        { pitch: 67, velocity: 73, startTime: 15.808, endTime: 16.448 },
        { pitch: 48, velocity: 70, startTime: 15.808, endTime: 17.216 },
        { pitch: 67, velocity: 72, startTime: 16.448, endTime: 17.248 },
        { pitch: 65, velocity: 73, startTime: 17.056, endTime: 17.696 },
        { pitch: 41, velocity: 63, startTime: 17.056, endTime: 18.752 },
        { pitch: 64, velocity: 74, startTime: 18.336000000000002, endTime: 18.976 },
        { pitch: 65, velocity: 71, startTime: 17.696, endTime: 19.072 },
        { pitch: 60, velocity: 73, startTime: 15.808, endTime: 19.52 },
        { pitch: 43, velocity: 68, startTime: 18.336000000000002, endTime: 19.616 },
        { pitch: 55, velocity: 65, startTime: 18.336000000000002, endTime: 19.616 },
        { pitch: 64, velocity: 74, startTime: 18.976, endTime: 19.968 },
        { pitch: 57, velocity: 67, startTime: 17.056, endTime: 20.288 },
        { pitch: 43, velocity: 68, startTime: 19.616, endTime: 20.896 },
        { pitch: 55, velocity: 67, startTime: 19.616, endTime: 21.024 },
        { pitch: 62, velocity: 75, startTime: 19.616, endTime: 21.152 },
        { pitch: 60, velocity: 72, startTime: 20.864, endTime: 21.504 },
        { pitch: 48, velocity: 69, startTime: 20.864, endTime: 22.112000000000002 },
        { pitch: 60, velocity: 71, startTime: 21.504, endTime: 22.112000000000002 },
        { pitch: 67, velocity: 75, startTime: 22.112000000000002, endTime: 22.752 },
        { pitch: 60, velocity: 71, startTime: 22.112000000000002, endTime: 23.392 },
        { pitch: 52, velocity: 67, startTime: 20.864, endTime: 23.424 },
        { pitch: 67, velocity: 71, startTime: 22.752, endTime: 23.616 },
        { pitch: 48, velocity: 65, startTime: 22.112000000000002, endTime: 23.744 },
        { pitch: 69, velocity: 75, startTime: 23.392, endTime: 24.032 },
        { pitch: 60, velocity: 68, startTime: 23.392, endTime: 24.64 },
        { pitch: 41, velocity: 59, startTime: 23.392, endTime: 25.632 },
        { pitch: 69, velocity: 72, startTime: 24.032, endTime: 25.92 },
        { pitch: 67, velocity: 72, startTime: 24.64, endTime: 26.208000000000002 },
        { pitch: 65, velocity: 72, startTime: 25.92, endTime: 26.560000000000002 },
        { pitch: 48, velocity: 69, startTime: 24.64, endTime: 26.624000000000002 },
        { pitch: 41, velocity: 63, startTime: 25.92, endTime: 27.584 },
        { pitch: 64, velocity: 73, startTime: 27.168, endTime: 27.808 },
        { pitch: 65, velocity: 70, startTime: 26.560000000000002, endTime: 27.968 },
        { pitch: 55, velocity: 64, startTime: 27.168, endTime: 28.448 },
        { pitch: 57, velocity: 68, startTime: 25.92, endTime: 28.48 },
        { pitch: 48, velocity: 63, startTime: 27.168, endTime: 28.608 },
        { pitch: 60, velocity: 67, startTime: 24.64, endTime: 28.64 },
        { pitch: 64, velocity: 73, startTime: 27.808, endTime: 28.64 },
        { pitch: 62, velocity: 75, startTime: 28.448, endTime: 29.088 },
        { pitch: 43, velocity: 68, startTime: 28.448, endTime: 29.76 },
        { pitch: 62, velocity: 71, startTime: 29.088, endTime: 29.952 },
        { pitch: 55, velocity: 67, startTime: 28.448, endTime: 29.984 },
        { pitch: 52, velocity: 67, startTime: 29.696, endTime: 30.976 },
        { pitch: 48, velocity: 69, startTime: 29.696, endTime: 31.04 },
        { pitch: 60, velocity: 71, startTime: 29.696, endTime: 33.28 },
    ],
    totalTime: 34,
});

export const DOUBLE_SCALE = new mm.NoteSequence({
    notes: [
        { pitch: 60, quantizedStartStep: 0, quantizedEndStep: 1, program: 0 },
        { pitch: 61, quantizedStartStep: 1, quantizedEndStep: 2, program: 0 },
        { pitch: 62, quantizedStartStep: 2, quantizedEndStep: 3, program: 0 },
        { pitch: 63, quantizedStartStep: 3, quantizedEndStep: 4, program: 0 },
        { pitch: 64, quantizedStartStep: 4, quantizedEndStep: 5, program: 0 },
        { pitch: 65, quantizedStartStep: 5, quantizedEndStep: 6, program: 0 },
        { pitch: 66, quantizedStartStep: 6, quantizedEndStep: 7, program: 0 },
        { pitch: 67, quantizedStartStep: 7, quantizedEndStep: 8, program: 0 },
        { pitch: 68, quantizedStartStep: 8, quantizedEndStep: 9, program: 0 },
        { pitch: 69, quantizedStartStep: 9, quantizedEndStep: 10, program: 0 },
        { pitch: 70, quantizedStartStep: 10, quantizedEndStep: 11, program: 0 },
        { pitch: 71, quantizedStartStep: 11, quantizedEndStep: 12, program: 0 },
        { pitch: 72, quantizedStartStep: 12, quantizedEndStep: 13, program: 0 },
        { pitch: 73, quantizedStartStep: 13, quantizedEndStep: 14, program: 0 },
        { pitch: 74, quantizedStartStep: 14, quantizedEndStep: 15, program: 0 },
        { pitch: 75, quantizedStartStep: 15, quantizedEndStep: 16, program: 0 },
        { pitch: 76, quantizedStartStep: 16, quantizedEndStep: 17, program: 0 },
        { pitch: 77, quantizedStartStep: 17, quantizedEndStep: 18, program: 0 },
        { pitch: 78, quantizedStartStep: 18, quantizedEndStep: 19, program: 0 },
        { pitch: 79, quantizedStartStep: 19, quantizedEndStep: 20, program: 0 },
        { pitch: 80, quantizedStartStep: 20, quantizedEndStep: 21, program: 0 },
        { pitch: 81, quantizedStartStep: 21, quantizedEndStep: 22, program: 0 },
        { pitch: 82, quantizedStartStep: 22, quantizedEndStep: 23, program: 0 },
        { pitch: 83, quantizedStartStep: 23, quantizedEndStep: 24, program: 0 },
    ],
    tempos: [{ time: 0, qpm: 140 }],
    keySignatures: [{ time: 0, key: 0 }],
    timeSignatures: [{ time: 0, numerator: 2, denominator: 4 }],
    totalQuantizedSteps: 24,
    quantizationInfo: { stepsPerQuarter: 2 },
});

export const STAFF_USE_CASES = new mm.NoteSequence({
    notes: [
        { pitch: 65, startTime: 0, endTime: 4, program: 0, velocity: 128 },
        { pitch: 65, startTime: 8, endTime: 10, program: 0, velocity: 112 },
        { pitch: 65, startTime: 12, endTime: 13, program: 0, velocity: 96 },
        { pitch: 65, startTime: 14, endTime: 14.5, program: 0, velocity: 80 },
        { pitch: 65, startTime: 15, endTime: 15.25, program: 0, velocity: 64 },
        { pitch: 65, startTime: 15.5, endTime: 15.625, program: 0, velocity: 48 },
        { pitch: 65, startTime: 15.75, endTime: 15.8125, program: 0, velocity: 32 },
        { pitch: 77, startTime: 15.875, endTime: 16.0625, program: 0 },
        { pitch: 65, startTime: 20, endTime: 22, program: 0 },
        { pitch: 77, startTime: 21, endTime: 23, program: 0 },
        { pitch: 65, startTime: 25, endTime: 25.5, program: 0 },
        { pitch: 66, startTime: 25.5, endTime: 26, program: 0 },
        { pitch: 66, startTime: 26, endTime: 26.5, program: 0 },
        { pitch: 65, startTime: 26.5, endTime: 27, program: 0 },
        { pitch: 65, startTime: 27, endTime: 27.5, program: 0 },
        { pitch: 66, startTime: 27.5, endTime: 28, program: 0 },
        { pitch: 66, startTime: 28, endTime: 32.5, program: 0 },
        { pitch: 66, startTime: 32.5, endTime: 33, program: 0 },
        { pitch: 66, startTime: 33, endTime: 36, program: 0 },
    ],
    tempos: [{ time: 0, qpm: 60 }],
    keySignatures: [{ time: 0, key: 0 }],
    timeSignatures: [{ time: 0, numerator: 4, denominator: 4 }],
    totalTime: 36,
});

export const ANNA_MAGDALENA_BACH = new mm.NoteSequence({
    ticksPerQuarter: 480,
    timeSignatures: [{ time: 0, numerator: 3, denominator: 4 }],
    tempos: [{ time: 0, qpm: 120 }],
    notes: [
        {
            pitch: 74,
            velocity: 128,
            startTime: 0,
            endTime: 0.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 67,
            velocity: 128,
            startTime: 0.5,
            endTime: 0.75,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 69,
            velocity: 128,
            startTime: 0.75,
            endTime: 1,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 71,
            velocity: 128,
            startTime: 1,
            endTime: 1.25,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 72,
            velocity: 128,
            startTime: 1.25,
            endTime: 1.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 74,
            velocity: 128,
            startTime: 1.5,
            endTime: 2,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 67,
            velocity: 128,
            startTime: 2,
            endTime: 2.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 67,
            velocity: 128,
            startTime: 2.5,
            endTime: 3,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 76,
            velocity: 128,
            startTime: 3,
            endTime: 3.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 72,
            velocity: 128,
            startTime: 3.5,
            endTime: 3.75,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 74,
            velocity: 128,
            startTime: 3.75,
            endTime: 4,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 76,
            velocity: 128,
            startTime: 4,
            endTime: 4.25,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 78,
            velocity: 128,
            startTime: 4.25,
            endTime: 4.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 79,
            velocity: 128,
            startTime: 4.5,
            endTime: 5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 67,
            velocity: 128,
            startTime: 5,
            endTime: 5.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 67,
            velocity: 128,
            startTime: 5.5,
            endTime: 6,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 72,
            velocity: 128,
            startTime: 6,
            endTime: 6.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 74,
            velocity: 128,
            startTime: 6.5,
            endTime: 6.75,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 72,
            velocity: 128,
            startTime: 6.75,
            endTime: 7,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 71,
            velocity: 128,
            startTime: 7,
            endTime: 7.25,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 69,
            velocity: 128,
            startTime: 7.25,
            endTime: 7.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 71,
            velocity: 128,
            startTime: 7.5,
            endTime: 8,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 72,
            velocity: 128,
            startTime: 8,
            endTime: 8.25,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 71,
            velocity: 128,
            startTime: 8.25,
            endTime: 8.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 69,
            velocity: 128,
            startTime: 8.5,
            endTime: 8.75,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 67,
            velocity: 128,
            startTime: 8.75,
            endTime: 9,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 66,
            velocity: 128,
            startTime: 9,
            endTime: 9.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 67,
            velocity: 128,
            startTime: 9.5,
            endTime: 9.75,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 69,
            velocity: 128,
            startTime: 9.75,
            endTime: 10,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 71,
            velocity: 128,
            startTime: 10,
            endTime: 10.25,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 67,
            velocity: 128,
            startTime: 10.25,
            endTime: 10.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 71,
            velocity: 128,
            startTime: 10.5,
            endTime: 11.25,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 69,
            velocity: 128,
            startTime: 11.25,
            endTime: 12,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 74,
            velocity: 128,
            startTime: 12,
            endTime: 12.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 67,
            velocity: 128,
            startTime: 12.5,
            endTime: 12.75,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 69,
            velocity: 128,
            startTime: 12.75,
            endTime: 13,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 71,
            velocity: 128,
            startTime: 13,
            endTime: 13.25,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 72,
            velocity: 128,
            startTime: 13.25,
            endTime: 13.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 74,
            velocity: 128,
            startTime: 13.5,
            endTime: 14,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 67,
            velocity: 128,
            startTime: 14,
            endTime: 14.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 67,
            velocity: 128,
            startTime: 14.5,
            endTime: 15,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 76,
            velocity: 128,
            startTime: 15,
            endTime: 15.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 72,
            velocity: 128,
            startTime: 15.5,
            endTime: 15.75,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 74,
            velocity: 128,
            startTime: 15.75,
            endTime: 16,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 76,
            velocity: 128,
            startTime: 16,
            endTime: 16.25,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 78,
            velocity: 128,
            startTime: 16.25,
            endTime: 16.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 79,
            velocity: 128,
            startTime: 16.5,
            endTime: 17,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 67,
            velocity: 128,
            startTime: 17,
            endTime: 17.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 67,
            velocity: 128,
            startTime: 17.5,
            endTime: 18,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 72,
            velocity: 128,
            startTime: 18,
            endTime: 18.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 74,
            velocity: 128,
            startTime: 18.5,
            endTime: 18.75,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 72,
            velocity: 128,
            startTime: 18.75,
            endTime: 19,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 71,
            velocity: 128,
            startTime: 19,
            endTime: 19.25,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 69,
            velocity: 128,
            startTime: 19.25,
            endTime: 19.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 71,
            velocity: 128,
            startTime: 19.5,
            endTime: 20,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 72,
            velocity: 128,
            startTime: 20,
            endTime: 20.25,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 71,
            velocity: 128,
            startTime: 20.25,
            endTime: 20.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 69,
            velocity: 128,
            startTime: 20.5,
            endTime: 20.75,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 67,
            velocity: 128,
            startTime: 20.75,
            endTime: 21,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 69,
            velocity: 128,
            startTime: 21,
            endTime: 21.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 71,
            velocity: 128,
            startTime: 21.5,
            endTime: 21.75,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 69,
            velocity: 128,
            startTime: 21.75,
            endTime: 22,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 67,
            velocity: 128,
            startTime: 22,
            endTime: 22.25,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 66,
            velocity: 128,
            startTime: 22.25,
            endTime: 22.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 67,
            velocity: 128,
            startTime: 22.5,
            endTime: 24,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 83,
            velocity: 128,
            startTime: 24,
            endTime: 24.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 79,
            velocity: 128,
            startTime: 24.5,
            endTime: 24.75,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 81,
            velocity: 128,
            startTime: 24.75,
            endTime: 25,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 83,
            velocity: 128,
            startTime: 25,
            endTime: 25.25,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 79,
            velocity: 128,
            startTime: 25.25,
            endTime: 25.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 81,
            velocity: 128,
            startTime: 25.5,
            endTime: 26,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 74,
            velocity: 128,
            startTime: 26,
            endTime: 26.25,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 76,
            velocity: 128,
            startTime: 26.25,
            endTime: 26.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 78,
            velocity: 128,
            startTime: 26.5,
            endTime: 26.75,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 74,
            velocity: 128,
            startTime: 26.75,
            endTime: 27,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 79,
            velocity: 128,
            startTime: 27,
            endTime: 27.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 76,
            velocity: 128,
            startTime: 27.5,
            endTime: 27.75,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 78,
            velocity: 128,
            startTime: 27.75,
            endTime: 28,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 79,
            velocity: 128,
            startTime: 28,
            endTime: 28.25,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 74,
            velocity: 128,
            startTime: 28.25,
            endTime: 28.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 73,
            velocity: 128,
            startTime: 28.5,
            endTime: 29,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 71,
            velocity: 128,
            startTime: 29,
            endTime: 29.25,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 73,
            velocity: 128,
            startTime: 29.25,
            endTime: 29.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 69,
            velocity: 128,
            startTime: 29.5,
            endTime: 30,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 69,
            velocity: 128,
            startTime: 30,
            endTime: 30.25,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 71,
            velocity: 128,
            startTime: 30.25,
            endTime: 30.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 73,
            velocity: 128,
            startTime: 30.5,
            endTime: 30.75,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 74,
            velocity: 128,
            startTime: 30.75,
            endTime: 31,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 76,
            velocity: 128,
            startTime: 31,
            endTime: 31.25,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 78,
            velocity: 128,
            startTime: 31.25,
            endTime: 31.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 79,
            velocity: 128,
            startTime: 31.5,
            endTime: 32,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 78,
            velocity: 128,
            startTime: 32,
            endTime: 32.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 76,
            velocity: 128,
            startTime: 32.5,
            endTime: 33,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 78,
            velocity: 128,
            startTime: 33,
            endTime: 33.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 69,
            velocity: 128,
            startTime: 33.5,
            endTime: 34,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 73,
            velocity: 128,
            startTime: 34,
            endTime: 34.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 74,
            velocity: 128,
            startTime: 34.5,
            endTime: 36,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 74,
            velocity: 128,
            startTime: 36,
            endTime: 36.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 67,
            velocity: 128,
            startTime: 36.5,
            endTime: 36.75,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 66,
            velocity: 128,
            startTime: 36.75,
            endTime: 37,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 67,
            velocity: 128,
            startTime: 37,
            endTime: 37.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 76,
            velocity: 128,
            startTime: 37.5,
            endTime: 38,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 67,
            velocity: 128,
            startTime: 38,
            endTime: 38.25,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 66,
            velocity: 128,
            startTime: 38.25,
            endTime: 38.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 67,
            velocity: 128,
            startTime: 38.5,
            endTime: 39,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 74,
            velocity: 128,
            startTime: 39,
            endTime: 39.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 72,
            velocity: 128,
            startTime: 39.5,
            endTime: 40,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 71,
            velocity: 128,
            startTime: 40,
            endTime: 40.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 69,
            velocity: 128,
            startTime: 40.5,
            endTime: 40.75,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 67,
            velocity: 128,
            startTime: 40.75,
            endTime: 41,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 66,
            velocity: 128,
            startTime: 41,
            endTime: 41.25,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 67,
            velocity: 128,
            startTime: 41.25,
            endTime: 41.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 69,
            velocity: 128,
            startTime: 41.5,
            endTime: 42,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 62,
            velocity: 128,
            startTime: 42,
            endTime: 42.25,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 64,
            velocity: 128,
            startTime: 42.25,
            endTime: 42.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 66,
            velocity: 128,
            startTime: 42.5,
            endTime: 42.75,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 67,
            velocity: 128,
            startTime: 42.75,
            endTime: 43,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 69,
            velocity: 128,
            startTime: 43,
            endTime: 43.25,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 71,
            velocity: 128,
            startTime: 43.25,
            endTime: 43.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 72,
            velocity: 128,
            startTime: 43.5,
            endTime: 44,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 71,
            velocity: 128,
            startTime: 44,
            endTime: 44.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 69,
            velocity: 128,
            startTime: 44.5,
            endTime: 45,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 71,
            velocity: 128,
            startTime: 45,
            endTime: 45.25,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 74,
            velocity: 128,
            startTime: 45.25,
            endTime: 45.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 67,
            velocity: 128,
            startTime: 45.5,
            endTime: 46,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 66,
            velocity: 128,
            startTime: 46,
            endTime: 46.5,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 59,
            velocity: 128,
            startTime: 46.5,
            endTime: 48,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 62,
            velocity: 128,
            startTime: 46.5,
            endTime: 48,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 67,
            velocity: 128,
            startTime: 46.5,
            endTime: 48,
            instrument: 0,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 55,
            velocity: 128,
            startTime: 0,
            endTime: 1,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 59,
            velocity: 128,
            startTime: 0,
            endTime: 1,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 62,
            velocity: 128,
            startTime: 0,
            endTime: 1,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 57,
            velocity: 128,
            startTime: 1,
            endTime: 1.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 59,
            velocity: 128,
            startTime: 1.5,
            endTime: 3,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 60,
            velocity: 128,
            startTime: 3,
            endTime: 4.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 59,
            velocity: 128,
            startTime: 4.5,
            endTime: 6,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 57,
            velocity: 128,
            startTime: 6,
            endTime: 7.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 55,
            velocity: 128,
            startTime: 7.5,
            endTime: 9,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 62,
            velocity: 128,
            startTime: 9,
            endTime: 9.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 59,
            velocity: 128,
            startTime: 9.5,
            endTime: 10,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 55,
            velocity: 128,
            startTime: 10,
            endTime: 10.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 62,
            velocity: 128,
            startTime: 10.5,
            endTime: 11,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 50,
            velocity: 128,
            startTime: 11,
            endTime: 11.25,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 60,
            velocity: 128,
            startTime: 11.25,
            endTime: 11.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 59,
            velocity: 128,
            startTime: 11.5,
            endTime: 11.75,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 57,
            velocity: 128,
            startTime: 11.75,
            endTime: 12,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 59,
            velocity: 128,
            startTime: 12,
            endTime: 13,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 57,
            velocity: 128,
            startTime: 13,
            endTime: 13.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 55,
            velocity: 128,
            startTime: 13.5,
            endTime: 14,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 59,
            velocity: 128,
            startTime: 14,
            endTime: 14.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 55,
            velocity: 128,
            startTime: 14.5,
            endTime: 15,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 60,
            velocity: 128,
            startTime: 15,
            endTime: 16.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 59,
            velocity: 128,
            startTime: 16.5,
            endTime: 17,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 60,
            velocity: 128,
            startTime: 17,
            endTime: 17.25,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 59,
            velocity: 128,
            startTime: 17.25,
            endTime: 17.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 57,
            velocity: 128,
            startTime: 17.5,
            endTime: 17.75,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 55,
            velocity: 128,
            startTime: 17.75,
            endTime: 18,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 57,
            velocity: 128,
            startTime: 18,
            endTime: 19,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 54,
            velocity: 128,
            startTime: 19,
            endTime: 19.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 55,
            velocity: 128,
            startTime: 19.5,
            endTime: 20.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 59,
            velocity: 128,
            startTime: 20.5,
            endTime: 21,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 60,
            velocity: 128,
            startTime: 21,
            endTime: 21.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 62,
            velocity: 128,
            startTime: 21.5,
            endTime: 22,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 50,
            velocity: 128,
            startTime: 22,
            endTime: 22.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 55,
            velocity: 128,
            startTime: 22.5,
            endTime: 23.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 43,
            velocity: 128,
            startTime: 23.5,
            endTime: 24,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 55,
            velocity: 128,
            startTime: 24,
            endTime: 25.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 54,
            velocity: 128,
            startTime: 25.5,
            endTime: 27,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 52,
            velocity: 128,
            startTime: 27,
            endTime: 27.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 55,
            velocity: 128,
            startTime: 27.5,
            endTime: 28,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 52,
            velocity: 128,
            startTime: 28,
            endTime: 28.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 57,
            velocity: 128,
            startTime: 28.5,
            endTime: 29.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 45,
            velocity: 128,
            startTime: 29.5,
            endTime: 30,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 57,
            velocity: 128,
            startTime: 30,
            endTime: 31.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 59,
            velocity: 128,
            startTime: 31.5,
            endTime: 32,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 62,
            velocity: 128,
            startTime: 32,
            endTime: 32.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 61,
            velocity: 128,
            startTime: 32.5,
            endTime: 33,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 62,
            velocity: 128,
            startTime: 33,
            endTime: 33.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 54,
            velocity: 128,
            startTime: 33.5,
            endTime: 34,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 57,
            velocity: 128,
            startTime: 34,
            endTime: 34.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 62,
            velocity: 128,
            startTime: 34.5,
            endTime: 35,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 50,
            velocity: 128,
            startTime: 35,
            endTime: 35.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 60,
            velocity: 128,
            startTime: 35.5,
            endTime: 36,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 59,
            velocity: 128,
            startTime: 36,
            endTime: 37,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 62,
            velocity: 128,
            startTime: 36.5,
            endTime: 37.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 59,
            velocity: 128,
            startTime: 37,
            endTime: 37.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 60,
            velocity: 128,
            startTime: 37.5,
            endTime: 38.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 64,
            velocity: 128,
            startTime: 38,
            endTime: 39,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 60,
            velocity: 128,
            startTime: 38.5,
            endTime: 39,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 59,
            velocity: 128,
            startTime: 39,
            endTime: 39.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 57,
            velocity: 128,
            startTime: 39.5,
            endTime: 40,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 55,
            velocity: 128,
            startTime: 40,
            endTime: 40.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 62,
            velocity: 128,
            startTime: 40.5,
            endTime: 41.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 50,
            velocity: 128,
            startTime: 42,
            endTime: 43.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 54,
            velocity: 128,
            startTime: 43,
            endTime: 43.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 52,
            velocity: 128,
            startTime: 43.5,
            endTime: 44,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 55,
            velocity: 128,
            startTime: 44,
            endTime: 44.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 54,
            velocity: 128,
            startTime: 44.5,
            endTime: 45,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 55,
            velocity: 128,
            startTime: 45,
            endTime: 45.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 47,
            velocity: 128,
            startTime: 45.5,
            endTime: 46,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 50,
            velocity: 128,
            startTime: 46,
            endTime: 46.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 55,
            velocity: 128,
            startTime: 46.5,
            endTime: 47,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 50,
            velocity: 128,
            startTime: 47,
            endTime: 47.5,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
        {
            pitch: 43,
            velocity: 128,
            startTime: 47.5,
            endTime: 48,
            instrument: 1,
            program: 1,
            isDrum: false,
        },
    ],
    totalTime: 48,
    sourceInfo: { encodingType: 3, parser: 6 },
});
